import type { Product } from "./productTypes";

export const PRODUCTS: Product[] = [
  {
    id: "aurora-sneakers",
    slug: "aurora-sneakers",
    brand: "Aurora",
    title: "Aurora Sneakers",
    description: "Lightweight knit runners with responsive cushioning for all-day comfort.",
    category: {
      id: "cat-footwear",
      name: "Footwear",
      description: "Shoes & sneakers",
      slug: "footwear",
    },
    images: [
      "https://picsum.photos/seed/aurora/600/600",
      "https://picsum.photos/seed/aurora/600/600?grayscale",
      "https://picsum.photos/seed/aurora2/600/600",
    ],
    options: [
      {
        id: "aurora-black",
        title: "Black / 42",
        images: ["https://picsum.photos/seed/aurora/600/600"],
        gallery: [
          "https://picsum.photos/seed/aurora/600/600",
          "https://picsum.photos/seed/aurora/600/600?grayscale",
          "https://picsum.photos/seed/aurora2/600/600",
        ],
        stockCount: 30,
        soldOut: 5,
        totalStock: 35,
        priceBeforeDiscount: 129,
        discountValue: 25.8,
        finalPrice: 103.2,
        attributes: [
          {
            id: "aurora-color-black",
            title: "Color",
            value: "Black",
            type: "COLOR",
            hex: "#1C1C1E",
          },
          { id: "aurora-size-42", title: "Size", value: "42", type: "SIZE" },
        ],
      },
      {
        id: "aurora-white",
        title: "White / 42",
        images: ["https://picsum.photos/seed/aurora/600/600?grayscale"],
        gallery: [
          "https://picsum.photos/seed/aurora/600/600",
          "https://picsum.photos/seed/aurora/600/600?grayscale",
          "https://picsum.photos/seed/aurora2/600/600",
        ],
        stockCount: 15,
        soldOut: 0,
        totalStock: 15,
        priceBeforeDiscount: 129,
        discountValue: 25.8,
        finalPrice: 103.2,
        attributes: [
          {
            id: "aurora-color-white",
            title: "Color",
            value: "White",
            type: "COLOR",
            hex: "#F5F5F0",
          },
          { id: "aurora-size-42", title: "Size", value: "42", type: "SIZE" },
        ],
      },
    ],
    directPrices: [
      { currencyCode: "USD", priceBeforeDiscount: 129, discountValue: 25.8, finalPrice: 103.2 },
    ],
    stockCount: 45,
    soldOut: 5,
    totalStock: 50,
    averageRating: 4.8,
    reviewCount: 213,
    isWishlist: false,
    badges: ["New"],
    freeShipping: true,
    ratingBreakdown: { 5: 170, 4: 32, 3: 8, 2: 2, 1: 1 },
    highlights: [
      "Responsive knit cushioning",
      "All-day comfort",
      "Breathable mesh upper",
      "Recycled materials",
    ],
    shipping: { freeThreshold: 0, etaDays: "2-4 days" },
    reviews: [
      {
        id: "rev-aurora-1",
        author: "Mika L.",
        rating: 5,
        date: "2026-06-12",
        title: "All-day comfort",
        body: "These are the most comfortable sneakers I have ever worn. The knit upper breathes well and the cushioning holds up through long days.",
        verified: true,
      },
      {
        id: "rev-aurora-2",
        author: "Sam T.",
        rating: 4,
        date: "2026-05-28",
        title: "Great fit, runs slightly narrow",
        body: "Love the responsive cushioning and the recycled materials feel premium. Runs a bit narrow so consider sizing up.",
        verified: true,
      },
      {
        id: "rev-aurora-3",
        author: "Jordan K.",
        rating: 5,
        date: "2026-04-15",
        title: "Perfect for daily runs",
        body: "Lightweight, breathable, and the cushioning is just right. My go-to pair for daily training.",
        verified: false,
      },
    ],
  },
  {
    id: "pulse-headphones",
    slug: "pulse-headphones",
    brand: "Pulse",
    title: "Pulse Wireless Headphones",
    description: "Over-ear headphones with active noise cancelling and 40h battery life.",
    category: {
      id: "cat-audio",
      name: "Audio",
      description: "Headphones & speakers",
      slug: "audio",
    },
    images: [
      "https://picsum.photos/seed/pulse/600/600",
      "https://picsum.photos/seed/pulse/600/600?grayscale",
      "https://picsum.photos/seed/pulse2/600/600",
    ],
    options: [
      {
        id: "pulse-graphite",
        title: "Graphite",
        images: ["https://picsum.photos/seed/pulse/600/600"],
        gallery: [
          "https://picsum.photos/seed/pulse/600/600",
          "https://picsum.photos/seed/pulse/600/600?grayscale",
          "https://picsum.photos/seed/pulse2/600/600",
        ],
        stockCount: 0,
        soldOut: 12,
        totalStock: 12,
        priceBeforeDiscount: 199,
        discountValue: 0,
        finalPrice: 199,
        attributes: [
          {
            id: "pulse-color-graphite",
            title: "Color",
            value: "Graphite",
            type: "COLOR",
            hex: "#3A3A3C",
          },
        ],
        flashSale: { isSale: true, id: "flash-pulse", data: null },
      },
      {
        id: "pulse-sand",
        title: "Sand",
        images: ["https://picsum.photos/seed/pulse/600/600?grayscale"],
        gallery: [
          "https://picsum.photos/seed/pulse/600/600",
          "https://picsum.photos/seed/pulse/600/600?grayscale",
          "https://picsum.photos/seed/pulse2/600/600",
        ],
        stockCount: 20,
        soldOut: 3,
        totalStock: 23,
        priceBeforeDiscount: 199,
        discountValue: 0,
        finalPrice: 199,
        attributes: [
          { id: "pulse-color-sand", title: "Color", value: "Sand", type: "COLOR", hex: "#D8C7A8" },
        ],
        flashSale: { isSale: true, id: "flash-pulse", data: null },
      },
    ],
    directPrices: [
      { currencyCode: "USD", priceBeforeDiscount: 199, discountValue: 0, finalPrice: 199 },
    ],
    stockCount: 20,
    soldOut: 15,
    totalStock: 35,
    averageRating: 4.6,
    reviewCount: 340,
    isWishlist: true,
    badges: ["Best Seller"],
    freeShipping: false,
    ratingBreakdown: { 5: 210, 4: 86, 3: 32, 2: 8, 1: 4 },
    highlights: [
      "Active noise cancelling",
      "40h battery life",
      "Comfortable over-ear fit",
      "Bluetooth 5.3",
    ],
    shipping: { freeThreshold: 150, etaDays: "2-3 days" },
    reviews: [
      {
        id: "rev-pulse-1",
        author: "Alex R.",
        rating: 5,
        date: "2026-06-10",
        title: "Noise cancelling is incredible",
        body: "The ANC blocks out everything on my commute. Battery easily lasts the full work week with heavy use.",
        verified: true,
      },
      {
        id: "rev-pulse-2",
        author: "Chris P.",
        rating: 4,
        date: "2026-05-22",
        title: "Great sound, clamp could be lighter",
        body: "Sound quality is excellent and the 40h battery is no joke. The clamp takes a day or two to break in.",
        verified: true,
      },
      {
        id: "rev-pulse-3",
        author: "Dana W.",
        rating: 5,
        date: "2026-04-03",
        title: "Best headphones I have owned",
        body: "Switched from a competing brand and the difference in noise cancelling and comfort is night and day.",
        verified: false,
      },
    ],
  },
  {
    id: "apex-watch",
    slug: "apex-watch",
    brand: "Apex",
    title: "Apex Fitness Watch",
    description:
      "GPS-enabled smartwatch with heart-rate monitoring, sleep tracking and a 7-day battery. Water resistant to 50m.",
    category: {
      id: "cat-wearables",
      name: "Wearables",
      description: "Smart watches",
      slug: "wearables",
    },
    images: [
      "https://picsum.photos/seed/apex/600/600",
      "https://picsum.photos/seed/apex/600/600?grayscale",
      "https://picsum.photos/seed/apex2/600/600",
    ],
    options: [
      {
        id: "apex-obsidian",
        title: "Obsidian",
        images: ["https://picsum.photos/seed/apex/600/600"],
        gallery: [
          "https://picsum.photos/seed/apex/600/600",
          "https://picsum.photos/seed/apex/600/600?grayscale",
          "https://picsum.photos/seed/apex2/600/600",
        ],
        stockCount: 40,
        soldOut: 8,
        totalStock: 48,
        priceBeforeDiscount: 249,
        discountValue: 24.9,
        finalPrice: 224.1,
        attributes: [
          {
            id: "apex-color-obsidian",
            title: "Color",
            value: "Obsidian",
            type: "COLOR",
            hex: "#212124",
          },
        ],
      },
      {
        id: "apex-titanium",
        title: "Titanium",
        images: ["https://picsum.photos/seed/apex/600/600?grayscale"],
        gallery: [
          "https://picsum.photos/seed/apex/600/600",
          "https://picsum.photos/seed/apex/600/600?grayscale",
          "https://picsum.photos/seed/apex2/600/600",
        ],
        stockCount: 25,
        soldOut: 0,
        totalStock: 25,
        priceBeforeDiscount: 249,
        discountValue: 24.9,
        finalPrice: 224.1,
        attributes: [
          {
            id: "apex-color-titanium",
            title: "Color",
            value: "Titanium",
            type: "COLOR",
            hex: "#C9C4BC",
          },
        ],
      },
      {
        id: "apex-orange",
        title: "Sunset Orange",
        images: ["https://picsum.photos/seed/apex2/600/600"],
        gallery: [
          "https://picsum.photos/seed/apex/600/600",
          "https://picsum.photos/seed/apex/600/600?grayscale",
          "https://picsum.photos/seed/apex2/600/600",
        ],
        stockCount: 10,
        soldOut: 2,
        totalStock: 12,
        priceBeforeDiscount: 249,
        discountValue: 24.9,
        finalPrice: 224.1,
        attributes: [
          {
            id: "apex-color-orange",
            title: "Color",
            value: "Sunset",
            type: "COLOR",
            hex: "#E9743C",
          },
        ],
      },
    ],
    directPrices: [
      { currencyCode: "USD", priceBeforeDiscount: 249, discountValue: 24.9, finalPrice: 224.1 },
      { currencyCode: "EUR", priceBeforeDiscount: 229, discountValue: 22.9, finalPrice: 206.1 },
    ],
    stockCount: 75,
    soldOut: 10,
    totalStock: 85,
    averageRating: 4.9,
    reviewCount: 512,
    isWishlist: false,
    badges: [],
    freeShipping: true,
    ratingBreakdown: { 5: 420, 4: 74, 3: 14, 2: 3, 1: 1 },
    highlights: [
      "GPS tracking",
      "Heart-rate monitoring",
      "Sleep tracking",
      "Water resistant to 50m",
    ],
    shipping: { freeThreshold: 0, etaDays: "3-5 days" },
    reviews: [
      {
        id: "rev-apex-1",
        author: "Riley N.",
        rating: 5,
        date: "2026-06-08",
        title: "GPS accuracy is spot on",
        body: "I have compared the GPS readings against dedicated running watches and the accuracy is within a few meters. Sleep tracking is detailed and useful.",
        verified: true,
      },
      {
        id: "rev-apex-2",
        author: "Morgan S.",
        rating: 5,
        date: "2026-05-30",
        title: "7-day battery is real",
        body: "With always-on display and daily GPS workouts I still get 6-7 days. The heart-rate monitoring is consistent and the water resistance gives peace of mind for pool workouts.",
        verified: true,
      },
      {
        id: "rev-apex-3",
        author: "Casey B.",
        rating: 4,
        date: "2026-04-20",
        title: "Solid fitness watch",
        body: "Great value for the features. The titanium finish feels premium and the sleep tracking has helped me understand my patterns better.",
        verified: false,
      },
    ],
  },
  {
    id: "terra-backpack",
    slug: "terra-backpack",
    brand: "Terra",
    title: "Terra Canvas Backpack",
    description:
      'Water-repellent canvas backpack with a padded 16" laptop sleeve and multiple compartments.',
    category: { id: "cat-bags", name: "Bags", description: "Backpacks & totes", slug: "bags" },
    images: [
      "https://picsum.photos/seed/terra/600/600",
      "https://picsum.photos/seed/terra/600/600?grayscale",
      "https://picsum.photos/seed/terra2/600/600",
    ],
    options: [
      {
        id: "terra-olive",
        title: "Olive",
        images: ["https://picsum.photos/seed/terra/600/600"],
        gallery: [
          "https://picsum.photos/seed/terra/600/600",
          "https://picsum.photos/seed/terra/600/600?grayscale",
          "https://picsum.photos/seed/terra2/600/600",
        ],
        stockCount: 8,
        soldOut: 4,
        totalStock: 12,
        priceBeforeDiscount: 89,
        discountValue: 13.35,
        finalPrice: 75.65,
        attributes: [
          {
            id: "terra-color-olive",
            title: "Color",
            value: "Olive",
            type: "COLOR",
            hex: "#6B705C",
          },
          { id: "terra-size-one", title: "Size", value: "One Size", type: "SIZE" },
        ],
      },
      {
        id: "terra-moss",
        title: "Moss",
        images: ["https://picsum.photos/seed/terra/600/600?grayscale"],
        gallery: [
          "https://picsum.photos/seed/terra/600/600",
          "https://picsum.photos/seed/terra/600/600?grayscale",
          "https://picsum.photos/seed/terra2/600/600",
        ],
        stockCount: 12,
        soldOut: 0,
        totalStock: 12,
        priceBeforeDiscount: 89,
        discountValue: 13.35,
        finalPrice: 75.65,
        attributes: [
          { id: "terra-color-moss", title: "Color", value: "Moss", type: "COLOR", hex: "#8A9B68" },
          { id: "terra-size-one", title: "Size", value: "One Size", type: "SIZE" },
        ],
      },
    ],
    directPrices: [
      { currencyCode: "USD", priceBeforeDiscount: 89, discountValue: 13.35, finalPrice: 75.65 },
    ],
    stockCount: 20,
    soldOut: 4,
    totalStock: 24,
    averageRating: 4.5,
    reviewCount: 128,
    isWishlist: true,
    badges: ["Limited"],
    freeShipping: true,
    ratingBreakdown: { 5: 78, 4: 34, 3: 12, 2: 3, 1: 1 },
    highlights: [
      "Water-repellent canvas",
      'Padded 16" laptop sleeve',
      "Multiple compartments",
      "Reinforced straps",
    ],
    shipping: { freeThreshold: 0, etaDays: "3-6 days" },
    reviews: [
      {
        id: "rev-terra-1",
        author: "Elliot G.",
        rating: 5,
        date: "2026-06-05",
        title: "Built to last",
        body: "The canvas is genuinely water-repellent and the laptop sleeve is well padded. Multiple compartments keep everything organized.",
        verified: true,
      },
      {
        id: "rev-terra-2",
        author: "Jamie L.",
        rating: 4,
        date: "2026-05-18",
        title: "Great everyday backpack",
        body: "Sturdy construction and the reinforced straps are comfortable even when fully loaded. The olive color is subtle and stylish.",
        verified: true,
      },
    ],
  },
];

export type ProductRowVariant = "single" | "nested";

export type ProductRowItem = {
  id: string;
  product: Product;
  variant: ProductRowVariant;
};

export const PRODUCT_ROWS: ProductRowItem[] = [
  { id: PRODUCTS[0].id, product: PRODUCTS[0], variant: "nested" },
  { id: PRODUCTS[1].id, product: PRODUCTS[1], variant: "nested" },
  { id: PRODUCTS[2].id, product: PRODUCTS[2], variant: "single" },
  { id: PRODUCTS[3].id, product: PRODUCTS[3], variant: "single" },
];
